FORMAT: 1A

# My Time API

## Group User

### Register [POST /user]

+ Request 

    + Attributes (object)

        + userName (string, required)

        + password (string, required)

        + email (string, required)

+ Response 201 (application/json; charset=utf-8)

    + Attributes (object)

        + token (string, required)

### Token [POST /user/token]

+ Request 

    + Attributes (object)

        + userName (string, required)

        + password (string, required)

+ Response 200 (application/json; charset=utf-8)

    + Attributes (object)

            + token (string, required)

## Group Timesheet

### Download Timesheet [GET /me/timesheet]

+ Request
    
    + Headers

            Authorization: Bearer {{token}}

    + Attributes (object)

        + date: `2018/03` (string, optional)

            Get this month timesheet yyyy/MM 

+ Response 200 (application/xlxs)

    + Body

            xlxs File

## Leave Day [/me/leave]

### Get Leave Day [GET /me/leave{?date}]

+ Parameters

    + date: `2018-03`

        Get specific month leave days, default is this month

+ Request 

    + Headers

            Authorization: Bearer {{token}}

+ Response 201 (application/json; charset=utf-8)

    + Attributes (object)

        + contents (array[object], required)

            + id: `1` (string, required)

            + date: `09/13/2018` (string, required)

            + reason (string, required)

### Add Leave Day [POST]

+ Request 

    + Headers

            Authorization: Bearer {{token}}

    + Attributes (object)

        + date: `09/13/2018` (string, required)

        + reason (string, required)

+ Response 201 (application/json; charset=utf-8)

    + Attributes (object)
    
        + id: `1` (string, required)

        + date: `09/13/2018` (string, required)

        + reason (string, required)

### Delete Leave Day [DELETE /me/leave/{leaveId}]

+ Parameters

    + leaveId: `1`

        Leave ID

+ Request 

    + Headers

            Authorization: Bearer {{token}}

    + Attributes (object)

        + date: `09/13/2018` (string, required)

        + reason (string, required)

+ Response 201 (application/json; charset=utf-8)

## Group Health Check 

### Ping [GET /ping]

+ Response 200 (application/json; charset=utf-8)

    + Body

            {"message": "OK"}
